### ISSUE TITLE
Ping Pong: Define this.endRound

### ISSUE THREAD

**Issue by DeathlyPlays** [DeathlyPlays/Exiled#100]
Ping Pong has a function called this.endRound that currently isn't defined...

**Comment by DeathlyPlays** [comment]
The server needs to restart because of a crash: TypeError: this.endRound is not a function
at Timeout._onTimeout (/home/ubuntu/workspace/game-cards/pingpong.js:80:16)
Please restart the server.
You will not be able to start new battles until the server restarts.

**Comment by DeathlyPlays** [comment]
@HoeenCoder we did define end round.... any clue as to why it isn't working?

**Comment by DeathlyPlays** [comment]
I could just remove the timer....

**Comment by HoeenCoder** [comment]
@DeathlyPlays its probably the `setTimeout` calling after `Console#destroy` is called, just add a check to the timeouts that confirms that the console is still on.

**Comment by DeathlyPlays** [comment]
Ah ok

**Comment by HoeenCoder** [comment]
forgot to assign before fixing lol

**Comment by DeathlyPlays** [comment]
Lol
