### ISSUE TITLE
Viewlogs are broken and crash

### ISSUE THREAD

**Issue by ghost** [DeathlyPlays/Exiled#104]
The server has crashed: TypeError: targets[u].trim is not a function
at CommandContext.viewlogs (/home/ubuntu/workspace/chat-plugins/viewlogs.js:13:51).

Credits to c7 for this: http://prnt.sc/f2pqer

**Comment by DeathlyPlays** [comment]
This occurs when a restart is needed

**Comment by ghost** [comment]
Oh ok
