### ISSUE TITLE
GitHub reverted...

### ISSUE THREAD

**Issue by DeathlyPlays** [DeathlyPlays/Exiled#124]

**Comment by DeathlyPlays** [comment]
@HoeenCoder is it possible to just revert to before I pushed the stuff from the github....

**Comment by HoeenCoder** [comment]
Yeah, assuming there was only 1 commit ``git reset HEAD~``

**Comment by HoeenCoder** [comment]
be very careful with that

**Comment by DeathlyPlays** [comment]
Ehhhh Im gonna just manually revert ig e.e

**Comment by DeathlyPlays** [comment]
We did lose a bit of code on the server and github but Im almost done
