### ISSUE TITLE
Type illusion loses type change on formchange

### ISSUE THREAD

**Issue by ghost** [DeathlyPlays/Exiled#154]

**Comment by ghost** [comment]
Also, I want to make sure that when there are dual types we can get the reverse of that type. For example: ghost/dark and another mon named dark/ghost

**Comment by DeathlyPlays** [comment]
- [x] Make type changes stay when a Pokemon forme changes/mega evolves.
- [x] Make type changes activate even if you name it backwards (For example: ghost/dark and another mon named dark/ghost)

**Comment by HiTechFlufi** [comment]
First box can be checked, as yesterday I fixed the bug where the type changed back after mega evolving

**Comment by ghost** [comment]
But what about form changes?

**Comment by DeathlyPlays** [comment]
We could test with Zygarde ---> Zygod

**Comment by DeathlyPlays** [comment]
We'd have to run a reverse function for the type recognition or manually do it, but seeing as this issue is solved for the most part I'm gonna close it
