### ISSUE TITLE
Refactor Metagames

### ISSUE THREAD

**Issue by ghost** [DeathlyPlays/Exiled#329]
New code standard requires us to make edits to our metas

**Comment by DeathlyPlays** [comment]
You wanna do it or me @Lycanium-Z

**Comment by DeathlyPlays** [comment]
Just assign yourself or me (whoever you decide)

**Comment by ghost** [comment]
Ok

**Comment by DeathlyPlays** [comment]
lol ok

**Comment by DeathlyPlays** [comment]
https://github.com/DeathlyPlays/Exiled/commit/05f1b2c705ae2fb02c35f2b35a7518e3c182a397

**Comment by DeathlyPlays** [comment]
Done

**Comment by ghost** [comment]
great

**Comment by DeathlyPlays** [comment]
:p
