### ISSUE TITLE
When making a new draft team, it crashes

### ISSUE THREAD

**Issue by ghost** [DeathlyPlays/Exiled#44]
Nuff said

**Comment by DeathlyPlays** [comment]
Who?

**Comment by Lord-Haji** [comment]
@Eelektross Crash Log Please ?

**Comment by ghost** [comment]
The server has crashed: TypeError: Cannot read property 'set' of undefined
at Draft.addTeam (/home/ubuntu/workspace/chat-plugins/drafts.js:33:15)

**Comment by Mystifi** [comment]
You guys are still using origindb; drafts.js is using nef syntax. Basically, wherever it says Db[fileName], you need to use Db(fileName)

**Comment by ghost** [comment]
Ah

**Comment by DeathlyPlays** [comment]
Thanks, I fixed it.
