### ISSUE TITLE
Travis Build the Code

### ISSUE THREAD

**Issue by DeathlyPlays** [DeathlyPlays/Exiled#6]

**Comment by NeonLightPWO** [comment]
or stop being lazy and test it locally

**Comment by DeathlyPlays** [comment]
This is a massive task @NeonLightPWO

**Comment by DeathlyPlays** [comment]
Tbh we are doing pretty damn good tbh I think in the next two days top we can knock this out :P

**Comment by HoeenCoder** [comment]
Im really busy atm

**Comment by ghost** [comment]
Nice, it'll be amazing to see this done

**Comment by ghost** [comment]
done apperently

**Comment by DeathlyPlays** [comment]
Finished tbh @Mystifi can you go back and fix the eslint errors in the files I temporarily put in eslintrc for you :p

**Comment by DeathlyPlays** [comment]
Its "finished"
