### ISSUE TITLE
Migrating Essb from c9

### ISSUE THREAD

**Issue by ghost** [DeathlyPlays/Exiled#79]
Due to the fact I suck at coding, there is a list of things I need migrated from the c9. This includes: Formats.js, moves.js, abilities.js, scripts.js, and items.js

- [ ] Fixing Almighty Bronzongs move

- [x] Migrate essb from c9 to repo

**Comment by ghost** [comment]
Side note: Almighty bronzong's move will not boost the user with stats. I am uncertain to make it a 50% chance

**Comment by DeathlyPlays** [comment]
Wdym

**Comment by ghost** [comment]
@DeathlyPlays Almighty Bronzong's should boost the user if the opponents stats are reset. It doesn't do that

**Comment by DeathlyPlays** [comment]
Hmm I think ik how

**Comment by DeathlyPlays** [comment]
On the function that would reset stats have it add boosts if it occurs e.e

**Comment by ghost** [comment]
Can you give me the code

**Comment by DeathlyPlays** [comment]
Idk the definite code thats just a rough guess

**Comment by DeathlyPlays** [comment]
Id test it with a self: { boosts:{ thing lol

**Comment by DeathlyPlays** [comment]
Fixed one error

**Comment by ghost** [comment]
K

**Comment by DeathlyPlays** [comment]
In my 3rd block Im gonna just git clone directly from the github and stuff and itll all be updated to the github?

**Comment by ghost** [comment]
Sure? Explain

**Comment by ghost** [comment]
Fixed the errors @DeathlyPlays

**Comment by DeathlyPlays** [comment]
I just updated the C9

**Comment by ghost** [comment]
K
